language: python

python: 2.7
env:
  - TOXENV=py27


install:
  - pip install -U tox

script:
  - tox

deploy:
  provider: pypi
  distributions: sdist
  user: scrapinghub
  password:
    secure: bG1ycgBJrVfgBsHAwaWScL2V1x52/aZy2znE2kFzFfYq95HS51mu1GO2PKwpATJyMCs/xUIKGhiBtoo8LzNmNU2kPgarQFwzpLkx2ninOm+3uAwuIfGGWsonBW/h854n+cNwppJOlfEOxvMVerVVpdV4EFeJfEkVYascwOBbnqo=
  on:
    tags: true
    repo: scrapinghub/exporters
    condition: $TOXENV == py27